# Generated by Django 5.0.1 on 2024-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naachiyar', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=250)),
            ],
        ),
    ]
