# Generated by Django 5.0.1 on 2024-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naachiyar', '0004_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobil', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.IntegerField(max_length=10)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
