# Generated by Django 5.0.1 on 2024-02-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naachiyar', '0005_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='mobil',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(),
        ),
    ]
