# Generated by Django 5.0.1 on 2024-02-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naachiyar', '0005_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='mobil',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(),
        ),
    ]
