# Generated by Django 4.2.5 on 2024-02-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Naachiyar', '0005_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='mobil',
            new_name='mobile',
        ),
    ]
