# Generated by Django 5.0.1 on 2024-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naachiyar', '0006_rename_mobil_job_mobile_alter_job_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
